name: Docker Image CI

on:
  push:
    branches: [ "release-4.0" ]
    
env:
  BUILD_VERSION: 4.0.1
  IMAGE_NAME: ${{ secrets.DOCKER_HUB_USERNAME }}/thingsboard

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 读取仓库内容
      uses: actions/checkout@v4
    - name: 安装 JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: 使用 Maven 构建 jar（跳过测试）
      run: mvn clean install -DskipTests
    - name: 将打好的 jar 复制为 Docker 构建使用名
      run: |
        mkdir docker-context
        cp application/target/thingsboard-${BUILD_VERSION}-boot.jar docker-context/
    - name: 设置 Docker Buildx
      uses: docker/setup-buildx-action@v3      
    - name: 登陆dockerhub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    - name: 构建并推送
      uses: docker/build-push-action@v5
      with:
        context: ./docker-context
        file: ./Dockerfile
        push: true
        tags: ${{ env.IMAGE_NAME }}:${{ env.BUILD_VERSION }}
        platforms: linux/amd64,linux/arm64
        build-args: |
          BUILD_VERSION=${{ env.BUILD_VERSION }}
