name: Docker Image CI

on:
  push:
    branches: [ "release-4.0" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 读取仓库内容
      uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build with Maven
      run: |
        mvn clean install -DskipTests
    # - name: 构建镜像
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
